package ng.upperlink.nibss.cmms.dto;

import ng.upperlink.nibss.cmms.enums.Constants;
import ng.upperlink.nibss.cmms.enums.MakerCheckerType;
import ng.upperlink.nibss.cmms.errorHandler.EnumConstraint;
import lombok.Data;
import org.hibernate.validator.constraints.NotBlank;


@Data
public class SubscriberRequest extends UserRequest {

    private Long id;

    //@NotBlank(message = "bank code is required.")
    private String bankCode;

    //@NotBlank(message = "bank account number is required.")
    private String bankAccountNumber;
    private String additionalInfo1;
    private String additionalInfo2;
    private String code;
    @NotBlank(message = "institution code is required.")
    private String institutionCode;
    private boolean autoGeneratedCode = true;

    @NotBlank(message = "user authorization type is required")
    @EnumConstraint(enumClass = MakerCheckerType.class, message = Constants.UNKNOWN_MAKER_CHECKER_TYPE)
    private String userAuthorisationType;
}
